//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DoAnEntities : DbContext
    {
        public DoAnEntities()
            : base("name=DoAnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_Category> tb_Category { get; set; }
        public DbSet<tb_Customer> tb_Customer { get; set; }
        public DbSet<tb_Order> tb_Order { get; set; }
        public DbSet<tb_OrderDetail> tb_OrderDetail { get; set; }
        public DbSet<tb_Product> tb_Product { get; set; }
        public DbSet<tb_Supplier> tb_Supplier { get; set; }
        public DbSet<tb_User> tb_User { get; set; }
        public DbSet<tb_UserRole> tb_UserRole { get; set; }
    }
}
