//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Customer
    {
        public tb_Customer()
        {
            this.tb_Order = new HashSet<tb_Order>();
        }
    
        public int customer_id { get; set; }
        public string customer_name { get; set; }
        public string email { get; set; }
        public string phone_number { get; set; }
        public string address { get; set; }
    
        public virtual ICollection<tb_Order> tb_Order { get; set; }
    }
}
