//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Product
    {
        public tb_Product()
        {
            this.tb_OrderDetail = new HashSet<tb_OrderDetail>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_description { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<double> product_price { get; set; }
        public Nullable<int> product_quantity { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual tb_Category tb_Category { get; set; }
        public virtual ICollection<tb_OrderDetail> tb_OrderDetail { get; set; }
        public virtual tb_Supplier tb_Supplier { get; set; }
    }
}
