//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Supplier
    {
        public tb_Supplier()
        {
            this.tb_Product = new HashSet<tb_Product>();
        }
    
        public int supplier_id { get; set; }
        public string supplier_name { get; set; }
        public string supplier_address { get; set; }
        public string supplier_email { get; set; }
        public string supplier_phone { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual ICollection<tb_Product> tb_Product { get; set; }
    }
}
